cabal-version:      3.0

name:           dutch-gov-accountability
version:        1.0.0
homepage:       https://github.com/jappeace/dutch-gov-accountability#readme
bug-reports:    https://github.com/jappeace/dutch-gov-accountability/issues
author:         Jappie Klooster
maintainer:     hi@jappie.me
copyright:      2025 Jappie Klooster
license:        MIT
license-file:   LICENSE
build-type:     Simple
synopsis:       CBS + Rijksfinancien public data collector for Dutch government spending

source-repository head
  type: git
  location: https://github.com/jappeace/dutch-gov-accountability

common common-options
  default-extensions:
      EmptyCase
      FlexibleContexts
      FlexibleInstances
      InstanceSigs
      MultiParamTypeClasses
      LambdaCase
      MultiWayIf
      NamedFieldPuns
      TupleSections
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveLift
      DeriveTraversable
      DerivingStrategies
      GeneralizedNewtypeDeriving
      StandaloneDeriving
      OverloadedStrings
      TypeApplications
      NumericUnderscores
      ImportQualifiedPost

  ghc-options:
    -O2 -Wall -Werror -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Widentities -Wredundant-constraints
    -Wcpp-undef -fwarn-tabs -Wpartial-fields
    -fdefer-diagnostics -Wunused-packages
    -fenable-th-splice-warnings
    -fno-omit-yields
    -threaded -rtsopts "-with-rtsopts=-N -M7G -T -Iw10"

  build-depends:
      base >=4.9.1.0 && <4.22.0

  default-language: Haskell2010

library
  import: common-options
  exposed-modules:
      DutchGov.CBS.Client
      DutchGov.CBS.ODataResponse
      DutchGov.CLI
      DutchGov.Database
      DutchGov.Rijksfinancien.BudgetTable
      DutchGov.Rijksfinancien.Client
      DutchGov.Schema
      DutchGov.Collector
  hs-source-dirs:
      src
  build-depends:
      aeson
    , bytestring
    , http-client
    , http-client-tls
    , http-types
    , monad-logger
    , optparse-applicative
    , persistent
    , persistent-sqlite
    , text
    , time

executable exe
  import: common-options
  main-is: Main.hs
  hs-source-dirs:
      app
  build-depends:
      dutch-gov-accountability
    , persistent-sqlite
    , text
  ghc-options: -Wno-unused-packages

test-suite unit
  import: common-options
  type: exitcode-stdio-1.0
  main-is: Test.hs
  ghc-options: -Wno-unused-packages
  other-modules:
      DutchGov.CBS.ODataResponseTest
      DutchGov.DatabaseTest
      DutchGov.Rijksfinancien.BudgetTableTest
  hs-source-dirs:
      test
  build-depends:
      aeson
    , dutch-gov-accountability
    , monad-logger
    , persistent
    , persistent-sqlite
    , tasty
    , tasty-hunit
